<link rel="stylesheet" type="text/css" href="${CONTEXT}css/easyui.css"/>
<link rel="stylesheet" type="text/css" href="${CONTEXT}css/global.css"/>
<link rel="stylesheet" type="text/css" href="${CONTEXT}css/icon.css"/>
<link rel="stylesheet" type="text/css" href="${CONTEXT}css/xlcm.css"/>
<link rel="stylesheet" type="text/css" href="${CONTEXT}css/xlcn.css"/>
<link rel="stylesheet" type="text/css" href="${CONTEXT}css/uploader.css"/>
<link rel="stylesheet" type="text/css" href="${CONTEXT}js/lightbox/css/lightbox.css"/>
<script type="text/javascript" src="${CONTEXT}js/jquery.min.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.form.js"></script>
<script type="text/javascript" src="${CONTEXT}js/common.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.easyui.min.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.validatebox.fixed.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.validate.js"></script>
<script type="text/javascript" src="${CONTEXT}js/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="${CONTEXT}js/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="${CONTEXT}js/moment.js"></script>
<script type="text/javascript">
var CONTEXT = "${CONTEXT}";
var imgUrlHost = "${imgUrlHost}";
</script>
